/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Home: typeof import('./src/components/home.vue')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpZoomIn: typeof import('~icons/ep/zoom-in')['default']
  }
}
