/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Home: typeof import('./src/components/home.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpHeadset: typeof import('~icons/ep/headset')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpZoomIn: typeof import('~icons/ep/zoom-in')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    UploadCard: typeof import('./src/components/UploadCard.vue')['default']
  }
}
